- id: cmake-missing-pytest-files
  name: Check for missing Pytest files
  description: Checks for Python unit tests which will not be run in automated tests.
  entry: cmake-missing-pytest-files
  language: python
  additional_dependencies: [gitpython]
  types: [python]

- id: mantid-release-note-check
  name: Release note bullet point style check
  description: Checks that release note bullet points are the correct style
  entry: mantid-release-note-check
  language: python
  stages: [commit]
